static char htmlDefaultHomePage[4500] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n"
"<title>Irrigation system</title>\n"
"<style>\n"
"html { font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center;}\n"
"body{margin-top: 50px;} h1 {color: #444444;margin: 50px auto 30px;} h3 {color: #444444;margin-bottom: 50px;}\n"
"p {font-size: 14px;color: #888;margin-bottom: 10px;}\n"
".button {display: block;width: 80px;background-color: #3498db;border: none;color: white;padding: 13px 30px;text-decoration: none;font-size: 25px;margin: 0px auto 35px;cursor: pointer;border-radius: 4px;}\n"
".button-on {background-color: #3498db;}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<p>Station 1 soil humidity 44 </p><a class=\"button button-on\" href=\"/station/on\">Hidrate</a>\n"
"<p>Station 2 soil humidity 12 </p><a class=\"button button-on\" href=\"/station/on\">Hidrate</a>\n"
"<p>Station 3 soil humidity 32 </p><a class=\"button button-on\" href=\"/station/on\">Hidrate</a>\n"
"<p>Station 4 soil humidity 92 </p><a class=\"button button-on\" href=\"/station/on\">Hidrate</a>\n"
"</body>\n"
"</html>\n";